//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class delivery
    {
        [Key]
        public int delivery_id { get; set; }
        [Range(1, int.MaxValue)]
        [Display(Name = "Номер заказа")]
        public Nullable<int> orderdelivery_id { get; set; }
        [Required]
        [Display(Name = "Имя получателя")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Фамилия получателя")]
        public string surname { get; set; }
        [Required]
        [Display(Name = "Вид доставки")]
        public string delivery_type { get; set; }
        [Required]
        [Display(Name = "Страна получателя")]
        public string country { get; set; }
        [Required]
        [Display(Name = "Город получателя")]
        public string city { get; set; }
        [Range(1, int.MaxValue)]
        [Display(Name = "Номер")]
        public Nullable<int> phone_number { get; set; }

        [Range(1, int.MaxValue)]
        [Display(Name = "Почтовый индекс")]
        public Nullable<int> postcode { get; set; }

        [Range(1, int.MaxValue)]
        [Display(Name = "Цена доставки")]
        public Nullable<int> cost { get; set; }
        [Required]
        [Display(Name = "Статус доставки")]
        public string delivery_status { get; set; }
        [Required]
        [Display(Name = "Адрес доставки")]
        public string adress { get; set; }

        public virtual order order { get; set; }
    }
}
