//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class order
    {
        public order()
        {
            this.delivery = new HashSet<delivery>();
            this.product = new HashSet<product>();
        }
        [Key]
        public int order_id { get; set; }

        public Nullable<System.DateTime> order_date { get; set; }
        public int userorder_id { get; set; }

        [Required]
        [Display(Name = "Способ оплаты")]
        public string payment_method { get; set; }
        [Required]
        [Display(Name = "Статус заказа")]
        public string orders_status { get; set; }

        public virtual ICollection<delivery> delivery { get; set; }
        public virtual ICollection<product> product { get; set; }

        [Range(1, int.MaxValue)]
        [Display(Name = "Итоговая сумма")]
        public Nullable<int> tax_sum { get; set; }
    
    }
}
