//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class storage
    {
        public storage()
        {
            this.product = new HashSet<product>();
        }
        [Key]
        public int storage_id { get; set; }
        [Range(1, int.MaxValue)]
        [Display(Name = "Количество товара на складе")]
        public Nullable<int> count_of_products { get; set; }
        [Required]
        [Display(Name = "Имя поставщика")]
        public string provider_name { get; set; }

        public virtual ICollection<product> product { get; set; }
    }
}
